---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024
    accelerate3d : false 

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  run_list:
  - recipe[yum::epel]
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
  run_list:
  - recipe[yum::epel]

suites:
- name: default
  run_list:
  - recipe[erlang]
  attributes: {}

- name: source
  run_list:
  - recipe[erlang]
  attributes:
    erlang:
      install_method: source
