---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024
###    cpus: 8
###    hwvirtex: off
###    hwvirtexexcl: off

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise32
    box_url: http://files.vagrantup.com/precise32.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: lucid32
    box_url: http://files.vagrantup.com/lucid32.box
  run_list:
  - recipe[apt]

suites:
###- name: default
###  run_list:
###  - recipe[erlang]
###  attributes: {}

- name: source
  run_list:
  - recipe[erlang]
  attributes:
    erlang:
      install_method: source
